import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Markads transCo",
  description: "Generated by create next app",
  icons: [ new URL("./images/logo.png", import.meta.url).toString() ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/x-icon" href="./images/logo.png" />

      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
