import Sidebar from "../components/sidebar";
import Header from "../components/header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Header />
      <div className="flex">
        <Sidebar />
        <div className="flex-grow p-5">
          {children}
        </div>
      </div>
    </div>
  );
}